version: "3.9"
services:
  # api:
  #   build: .
  #   container_name: fastapi_app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    container_name: test_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - test_data:/var/lib/postgresql/data

volumes:
  test_data:


# # version: "3.9"
# services:
#   db:
#     image: postgres:15
#     container_name: test_db
#     restart: always
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - test_data:/var/lib/postgresql/data

# volumes:
#   test_data:

